name: highty_inventory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  iconify_flutter: ^0.0.5
  json_annotation: ^4.9.0
  mobile_scanner: ^5.1.1
  pretty_qr_code: ^3.3.0
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/stocks/
    - .env
